### PR TITLE
create-dev-platform: use correct env_name_file to destroy platform-terraform on_failure

### PR DESCRIPTION
**Pull request by anukul**
See failed build [#420](https://concourse.storyscript-ci.com/teams/main/pipelines/dev-platforms/jobs/create-dev-platform/builds/420#L5e39865a:1)

### CODE REVIEW

**Comment by anukul** [comment]
Do we actually need the destroy step `on_failure`, given that `delete_on_failure: true` in the `put` step?

**Comment by williammartin** [comment]
@anukul Can you point to the build that failed because the `env_name` was incorrect?

**Comment by anukul** [comment]
Linked build [#420](https://concourse.storyscript-ci.com/teams/main/pipelines/dev-platforms/jobs/create-dev-platform/builds/420#L5e39865a:1) reads `Failed to read 'env_name_file': open platform-terraform/name: no such file or directory
`

I don't know why this happened, and this PR was an attempt to correctly fetch the `env_name_file` from `github-apps-pool/name` which I found from its use in the `put: platform-terraform` step.

**Comment by williammartin** [comment]
Thanks!

**Comment by williammartin** [comment]
Do you want me to `fly set-pipeline` this change?

**Comment by anukul** [comment]
Sure, thank you.

**Comment by anukul** [comment]
Also, it looks like we can remove this `destroy` step from the `on_failure` block since it is covered by `put.params.delete_on_failure: true` in the `do` block above.

Should I make that change?

**Pull request merged**
