### PR TITLE
Tag images with git tag

### PR DESCRIPTION
**Pull request by anukul**
This should result in docker images being built from git tags for all resources

### CODE REVIEW

**Comment by williammartin** [comment]
This LGTM at a quick glance. Are you familiar with `fly set-pipeline` yet?

**Comment by williammartin** [comment]
Well, if I understand this it will look at each git commit that comes through on each of our repos, then look to see whether there is a git tag associates or not. If there is it tags the image with that tag and latest, otherwise only latest?

**Comment by anukul** [comment]
That is correct.

I'm familiar with `fly`, but I'm not sure how the parameters (docker credentials) are passed in this pipeline.

**Comment by williammartin** [comment]
Yes we should be, but we are not. I've been providing them on the command line, having fetched them from the shared folder in lastpass.

**Comment by anukul** [comment]
Cool.

I fixed some stupid bugs (no `+x` on the script and a typo), set the pipeline and things seems to work!

**Pull request merged**
